
%% Prepare reduced-form estimator 

% Create a reduced-form estimator object
estimator = estimator.?ESTIMATOR?( ...
    meta ...
    , ?ESTIMATOR_SETTINGS?
);


%% Create reduced-form model 

% Assemble a reduced-form model from the components
redModel = ReducedForm( ...
    Meta=meta ...
    , DataHolder=dataHolder ...
    , Estimator=estimator ...
    , Dummies=dummyObjects ...
);
printObject(redModel);

