
function modules = getModules()

    modules = [
        "base", ...
        "cross", ...
        "separable", ...
        "threshold", ...
        "mixed", ...
        ... "factor", ...
        ... "meanadj", ...
    ];

end%

